'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase';
import AppSidebar from '@/components/AppSidebar';

type Subject={id:string;name:string;slug:string;icon:string;sort_order:number};
type Topic={id:string;subject_id:string;name:string;slug:string;sort_order:number};
export default function CurriculumAdmin(){
 const supabase=createClient(); const [subjects,setSubjects]=useState<Subject[]>([]),[topics,setTopics]=useState<Topic[]>([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[slug,setSlug]=useState(''),[topicName,setTopicName]=useState(''),[topicSlug,setTopicSlug]=useState(''),[message,setMessage]=useState('');
 async function load(){const [{data:s},{data:t}]=await Promise.all([supabase.from('subjects').select('*').order('sort_order'),supabase.from('topics').select('*').order('sort_order')]);setSubjects(s??[]);setTopics(t??[]);}
 useEffect(()=>{load()},[]);
 async function addSubject(){setMessage('');const r=await fetch('/api/admin/subjects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,slug,icon:'📚'})});const d=await r.json();if(!r.ok){setMessage(d.error||'Xato');return;}setName('');setSlug('');setMessage('Fan qo‘shildi');load();}
 async function addTopic(){setMessage('');if(!selected){setMessage('Avval fan tanlang');return;}const r=await fetch('/api/admin/topics',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subject_id:selected,name:topicName,slug:topicSlug})});const d=await r.json();if(!r.ok){setMessage(d.error||'Xato');return;}setTopicName('');setTopicSlug('');setMessage('Mavzu qo‘shildi');load();}
 async function remove(path:string,id:string){if(!confirm('O‘chirishni tasdiqlaysizmi?'))return;const r=await fetch(`${path}?id=${id}`,{method:'DELETE'});const d=await r.json();setMessage(r.ok?'O‘chirildi':d.error||'Xato');load();}
 return <main className="dashboard-layout"><AppSidebar/><div className="dashboard-content"><section className="dash-wrap"><div className="kicker">ADMIN · CURRICULUM</div><h1>Fanlar va mavzular</h1><p className="lead">O‘quv dasturini admin sifatida boshqaring.</p><div className="dash-grid"><section className="panel"><h2>Yangi fan</h2><input placeholder="Fan nomi" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="slug: matematika" value={slug} onChange={e=>setSlug(e.target.value)}/><button className="primary" onClick={addSubject}>Qo‘shish</button><div className="list">{subjects.map(s=><div className="recent-row" key={s.id}><b>{s.icon} {s.name}</b><small>{s.slug}</small><button className="secondary" onClick={()=>remove('/api/admin/subjects',s.id)}>O‘chirish</button></div>)}</div></section><section className="panel"><h2>Yangi mavzu</h2><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Fan tanlang</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input placeholder="Mavzu nomi" value={topicName} onChange={e=>setTopicName(e.target.value)}/><input placeholder="slug" value={topicSlug} onChange={e=>setTopicSlug(e.target.value)}/><button className="primary" onClick={addTopic}>Qo‘shish</button><div className="list">{topics.map(t=><div className="recent-row" key={t.id}><b>{t.name}</b><small>{subjects.find(s=>s.id===t.subject_id)?.name||'—'}</small><button className="secondary" onClick={()=>remove('/api/admin/topics',t.id)}>O‘chirish</button></div>)}</div></section></div>{message&&<div className="error-box">{message}</div>}</section></div></main>;
}
