import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import AppSidebar from '@/components/AppSidebar';

export default async function QuestionBank({searchParams}:{searchParams:Promise<{subject?:string;difficulty?:string;topic?:string}>}){
  const p=await searchParams; const supabase=await createClient();
  const {data:subjects}=await supabase.from('subjects').select('id,name,slug').order('sort_order');
  const subject=(subjects??[]).find((s:any)=>s.slug===p.subject);
  const {data:topics}=subject?await supabase.from('topics').select('id,name,slug').eq('subject_id',subject.id).order('sort_order'):({data:[]} as any);
  let query=supabase.from('questions').select('id,text,difficulty,explanation,topic_id,topics(name,slug,subjects(name,slug)),question_options(id,text,key,sort_order)').eq('status','published').order('created_at',{ascending:false}).limit(50);
  if(subject)query=query.eq('topics.subject_id',subject.id);
  if(p.topic){const topic=(topics??[]).find((t:any)=>t.slug===p.topic);if(topic)query=query.eq('topic_id',topic.id);}
  if(p.difficulty)query=query.eq('difficulty',p.difficulty);
  const {data:questions,error}=await query;
  return <main className="dashboard-layout"><AppSidebar/><div className="dashboard-content"><header className="dashboard-topbar"><div className="dashboard-mobile-brand"><span className="brand-mark">N</span> National Certificate AI</div><nav><Link href="/dashboard">Home</Link><Link href="/practice">Practice</Link><Link href="/study-plan">Study Plan</Link></nav></header><section className="subject-wrap"><div className="section-heading"><div><div className="kicker">QUESTION BANK</div><h1>Savollar bazasi</h1><p>Fan, mavzu va qiyinlik darajasini tanlab savollarni ko‘ring.</p></div><Link className="primary" href="/practice">Practice →</Link></div><form className="form-card qb-filters" method="get"><label>Fan<select name="subject" defaultValue={p.subject||''}><option value="">Barcha fanlar</option>{(subjects??[]).map((s:any)=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select></label><label>Mavzu<select name="topic" defaultValue={p.topic||''}><option value="">Barcha mavzular</option>{(topics??[]).map((t:any)=><option key={t.slug} value={t.slug}>{t.name}</option>)}</select></label><label>Qiyinlik<select name="difficulty" defaultValue={p.difficulty||''}><option value="">Barchasi</option><option value="easy">Oson</option><option value="medium">O‘rta</option><option value="hard">Qiyin</option></select></label><button className="primary" type="submit">Filtrlash →</button></form>{error&&<div className="error-box">Savollarni yuklashda xatolik yuz berdi.</div>}<div className="question-bank-list">{(questions??[]).map((q:any,i:number)=><article className="panel bank-question" key={q.id}><div className="question-meta"><span>{i+1}. {(q.topics as any)?.name||'Mavzu'}</span><span className={`difficulty ${q.difficulty}`}>{q.difficulty==='easy'?'OSON':q.difficulty==='medium'?'O‘RTA':'QIYIN'}</span></div><h2>{q.text}</h2><div className="bank-options">{(q.question_options??[]).sort((a:any,b:any)=>(a.sort_order??0)-(b.sort_order??0)).map((o:any)=><div key={o.id}><b>{o.key}</b>{o.text}</div>)}</div><details><summary>Tushuntirish</summary><p>{q.explanation||'Tushuntirish hali qo‘shilmagan.'}</p></details></article>)}{!(questions??[]).length&&<div className="result-card"><h2>Hozircha savol yo‘q</h2><p>Tanlangan filtrlar bo‘yicha savollar bazaga qo‘shilmagan. Materiallar qo‘shilgach shu yerda chiqadi.</p></div>}</div></section></div></main>}
