import Link from 'next/link';

const subjects = [
  ['Matematika', '∑', 'Aniq fanlar', '/subjects/matematika'],
  ['Tarix', '◈', 'Ijtimoiy fanlar', '/subjects/tarix'],
  ['Kimyo', '⚗', 'Tabiiy fanlar', '/subjects/kimyo'],
  ['Biologiya', '⌬', 'Tabiiy fanlar', '/subjects/biologiya'],
  ['Ona tili va adabiyot', 'Aa', 'Til va adabiyot', '/subjects/ona-tili-adabiyot'],
];

const features = [
  ['01', 'Practice', 'Fan va mavzuni tanlang, vaqtni belgilang va savollarni imtihon ritmida ishlang.'],
  ['02', 'Question Bank', 'Savollarni fan, mavzu va Oson / O‘rta / Qiyin daraja bo‘yicha toping.'],
  ['03', 'Natijalar', 'Aniqlik, yechilgan savollar va mavzular bo‘yicha o‘sishingizni kuzating.'],
  ['04', 'Study Plan', 'Imtihon sanasi va maqsadli darajangizga mos reja tuzing.'],
];

const steps = [
  ['01', 'Maqsadni belgilang', 'Imtihon sanasi va C dan A+ gacha maqsadli natijani tanlang.'],
  ['02', 'Fanni tanlang', 'Kerakli faningizni oching va tayyorgarlik usulini tanlang.'],
  ['03', 'Muntazam mashq qiling', 'Savollarni yeching, vaqt bilan ishlang va natijani tekshiring.'],
  ['04', 'Rivojlanishni kuzating', 'Zaif mavzularni aniqlang va reja asosida qayta ishlang.'],
];

export default function Home() {
  return (
    <main className="landing">
      <style>{`
        .landing{--ink:#1d1814;--ink-soft:#302720;--muted:#71675e;--bronze:#b8894a;--bronze-dark:#8b6333;--cream:#faf8f3;--paper:#fffdf9;--beige:#f1e8dc;--line:#e5dacb;min-height:100vh;background:var(--cream);color:var(--ink);overflow:hidden;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.landing *{box-sizing:border-box}.landing a{text-decoration:none;color:inherit}
        .topbar{position:sticky;top:12px;z-index:50;width:min(1160px,calc(100% - 32px));height:68px;margin:14px auto 0;padding:0 10px 0 17px;display:flex;align-items:center;justify-content:space-between;gap:20px;border:1px solid rgba(184,137,74,.22);border-radius:19px;background:rgba(255,253,249,.82);backdrop-filter:blur(18px);box-shadow:0 12px 40px rgba(54,42,29,.06)}
        .brand{display:flex;align-items:center;gap:10px;font-size:17px;font-weight:850;letter-spacing:-.04em}.brand-mark{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:var(--ink);color:#f5e6d0;font:600 20px Georgia,serif;box-shadow:0 7px 16px rgba(29,24,20,.15)}.navlinks{display:flex;gap:30px;color:#756b61;font-size:12px;font-weight:700}.navlinks a:hover{color:var(--bronze-dark)}.nav-actions{display:flex;align-items:center;gap:8px}.login-link{padding:11px 14px;color:#675d54!important;font-size:12px;font-weight:750}.nav-cta{padding:12px 18px;border-radius:11px;background:var(--ink);color:#fff!important;font-size:12px;font-weight:850;transition:.2s}.nav-cta:hover{transform:translateY(-2px);background:#30261f}
        .hero{position:relative;width:min(1160px,calc(100% - 32px));min-height:720px;margin:auto;padding:80px 20px 55px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.hero-bg{position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 50% 38%,rgba(184,137,74,.19),transparent 31%),radial-gradient(circle at 9% 55%,rgba(230,214,193,.35),transparent 26%),radial-gradient(circle at 91% 55%,rgba(240,226,207,.45),transparent 25%)}.hero-grid{position:absolute;inset:0;pointer-events:none;background-image:linear-gradient(rgba(184,137,74,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(184,137,74,.045) 1px,transparent 1px);background-size:56px 56px;mask-image:linear-gradient(to bottom,#000,transparent 82%)}.hero>*:not(.hero-bg):not(.hero-grid){position:relative;z-index:2}.eyebrow{display:inline-flex;align-items:center;gap:9px;padding:9px 14px;border:1px solid #ded1c0;border-radius:999px;background:rgba(255,253,249,.9);color:#786d63;font-size:9px;font-weight:900;letter-spacing:.15em;box-shadow:0 8px 24px rgba(65,48,31,.05)}.dot{width:6px;height:6px;border-radius:50%;background:var(--bronze);box-shadow:0 0 0 4px #f0e4d4}.hero h1{max-width:980px;margin:25px 0 18px;font:600 clamp(54px,7.4vw,94px)/.91 Georgia,"Times New Roman",serif;letter-spacing:-.065em}.hero h1 em{display:block;color:var(--bronze-dark);font-style:italic}.hero-sub{max-width:650px;margin:0;color:var(--muted);font-size:15px;line-height:1.85}.actions{display:flex;gap:10px;margin-top:31px}.button{display:inline-flex;align-items:center;justify-content:center;gap:9px;border-radius:12px;font-size:12px;font-weight:850;transition:.22s}.button-main{padding:15px 23px;background:var(--bronze-dark);color:#fff!important;box-shadow:0 14px 30px rgba(139,99,51,.2)}.button-main:hover{transform:translateY(-3px);background:#75532d}.button-ghost{padding:14px 20px;border:1px solid #d7cabc;background:rgba(255,255,255,.62)}.button-ghost:hover{transform:translateY(-3px);background:#fff;border-color:#bda47e}.proof{display:flex;flex-wrap:wrap;justify-content:center;gap:8px;margin-top:22px}.proof span{padding:7px 11px;border:1px solid rgba(184,137,74,.2);border-radius:999px;background:rgba(255,255,255,.55);color:#84786d;font-size:10px;font-weight:700}.scrollhint{margin-top:38px;color:#a1988e;font-size:8px;font-weight:850;letter-spacing:.16em}.scrollhint b{display:block;margin-top:4px;font-size:16px;font-weight:400}
        .section{width:min(1160px,calc(100% - 32px));margin:auto;padding:98px 20px}.section-head{display:flex;align-items:end;justify-content:space-between;gap:55px;margin-bottom:34px}.eyebrow-small{font-size:9px;font-weight:900;letter-spacing:.18em;color:var(--bronze-dark)}.section h2{max-width:700px;margin:9px 0 0;font:600 clamp(38px,4.8vw,61px)/1 Georgia,serif;letter-spacing:-.055em}.section-head p{max-width:410px;margin:0;color:var(--muted);font-size:13px;line-height:1.8}
        .subjects{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.subject{grid-column:span 2;min-height:218px;padding:24px;border:1px solid var(--line);border-radius:21px;background:var(--paper);position:relative;overflow:hidden;transition:.25s;box-shadow:0 8px 28px rgba(58,43,28,.035)}.subject:nth-child(4){grid-column:2/span 2}.subject:nth-child(5){grid-column:4/span 2}.subject:before{content:"";position:absolute;width:180px;height:180px;right:-100px;top:-100px;border-radius:50%;background:var(--beige)}.subject:hover{transform:translateY(-7px);border-color:#cdb08a;box-shadow:0 25px 50px rgba(58,43,28,.11)}.subject-icon{width:51px;height:51px;display:grid;place-items:center;border-radius:15px;background:var(--beige);color:var(--bronze-dark);font:22px Georgia,serif;margin-bottom:31px;position:relative}.subject small{color:#9a8d81;font-size:10px;font-weight:750}.subject h3{margin:7px 0 0;font-size:18px;letter-spacing:-.035em}.subject-arrow{position:absolute;right:20px;bottom:18px;color:#9b8c7e;font-size:20px;transition:.2s}.subject:hover .subject-arrow{transform:translateX(6px);color:var(--bronze-dark)}
        .showcase{border-top:1px solid var(--line);border-bottom:1px solid var(--line);background:#f1eae1}.feature-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.feature{min-height:242px;padding:25px;border:1px solid #ddd1c1;border-radius:19px;background:rgba(255,255,255,.68);transition:.23s}.feature:hover{background:#fff;transform:translateY(-6px);box-shadow:0 20px 38px rgba(58,43,28,.08)}.feature-number{color:var(--bronze-dark);font-size:10px;font-weight:900}.feature h3{margin:62px 0 10px;font-size:19px;letter-spacing:-.035em}.feature p{margin:0;color:var(--muted);font-size:12px;line-height:1.75}
        .workflow{display:grid;grid-template-columns:.85fr 1.25fr;gap:80px;align-items:center}.workflow-copy p{max-width:480px;color:var(--muted);font-size:14px;line-height:1.9}.steps{display:grid;gap:11px}.step{display:flex;gap:15px;padding:19px;border:1px solid var(--line);border-radius:17px;background:var(--paper);transition:.2s}.step:hover{transform:translateX(5px);border-color:#cdb08a;box-shadow:0 12px 28px rgba(58,43,28,.05)}.step-number{width:33px;height:33px;flex:none;display:grid;place-items:center;border-radius:10px;background:var(--ink);color:#f6e7d1;font-size:9px;font-weight:850}.step h3{margin:0 0 4px;font-size:15px}.step p{margin:0;color:#857a70;font-size:11px;line-height:1.65}
        .mini-dashboard{margin-top:40px;padding:15px;border:1px solid var(--line);border-radius:23px;background:#f0e8dd;box-shadow:0 20px 50px rgba(55,42,28,.07)}.dash-window{border:1px solid #dfd4c6;border-radius:17px;background:#fffdf9;overflow:hidden}.dash-head{height:48px;padding:0 16px;border-bottom:1px solid #eee6db;display:flex;align-items:center;justify-content:space-between}.dash-head b{font-size:12px}.dash-dots{display:flex;gap:5px}.dash-dots i{width:6px;height:6px;border-radius:50%;background:#d9cfc3}.dash-body{display:grid;grid-template-columns:1.2fr .8fr;gap:10px;padding:12px}.dash-card{border:1px solid #eee5da;border-radius:13px;padding:14px;background:#fff}.dash-card small{color:#998d82;font-size:9px}.dash-card strong{display:block;margin-top:7px;font:600 27px Georgia,serif}.dash-line{height:7px;border-radius:99px;background:#eee7df;margin-top:12px;overflow:hidden}.dash-line span{display:block;width:72%;height:100%;background:var(--bronze)}
        .cta{width:min(1120px,calc(100% - 32px));margin:0 auto 75px;padding:57px;border-radius:29px;background:var(--ink);color:#fff;display:flex;align-items:center;justify-content:space-between;gap:35px;position:relative;overflow:hidden;box-shadow:0 28px 65px rgba(33,29,24,.16)}.cta:before{content:"";position:absolute;width:580px;height:580px;right:-230px;top:-300px;border-radius:50%;border:1px solid rgba(255,255,255,.08);box-shadow:0 0 0 60px rgba(255,255,255,.025),0 0 0 120px rgba(255,255,255,.015)}.cta>*{position:relative;z-index:1}.cta .eyebrow-small{color:#d9b87e}.cta h2{color:#fff;margin-top:9px}.cta .button-main{background:#bd9358}.cta .button-main:hover{background:#d0a46a}
        footer{width:min(1120px,calc(100% - 32px));margin:auto;padding:26px 0 42px;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:25px;color:#94887c;font-size:10px}footer strong{color:#594d43;font-size:12px}footer .footer-links{display:flex;gap:20px}footer a:hover{color:var(--bronze-dark)}
        @media(max-width:900px){.navlinks{display:none}.subjects{grid-template-columns:repeat(2,1fr)}.subject,.subject:nth-child(4),.subject:nth-child(5){grid-column:auto}.feature-grid{grid-template-columns:repeat(2,1fr)}.workflow{grid-template-columns:1fr;gap:40px}.section-head{display:block}.section-head p{margin-top:17px}}
        @media(max-width:620px){.topbar{width:calc(100% - 18px);height:62px;margin-top:7px;top:7px}.brand{font-size:14px}.brand-mark{width:34px;height:34px}.login-link{display:none}.nav-cta{padding:10px 13px}.hero{width:100%;min-height:670px;padding:72px 18px 48px}.hero h1{font-size:48px}.hero-sub{font-size:14px}.actions{width:100%;flex-direction:column}.actions>*{width:100%}.section{width:100%;padding:72px 18px}.subjects,.feature-grid{grid-template-columns:1fr}.subject,.subject:nth-child(4),.subject:nth-child(5){grid-column:auto}.feature{min-height:200px}.feature h3{margin-top:38px}.mini-dashboard{margin-top:28px}.dash-body{grid-template-columns:1fr}.cta{width:calc(100% - 36px);padding:39px 25px;display:grid;justify-items:center;text-align:center;margin-bottom:52px}.cta .button-main{width:100%}footer{width:calc(100% - 36px);display:grid;gap:13px}footer .footer-links{flex-wrap:wrap}}
      `}</style>

      <nav className="topbar">
        <Link href="/" className="brand"><span className="brand-mark">M</span><span>MilliyTest</span></Link>
        <div className="navlinks"><a href="#subjects">Fanlar</a><a href="#features">Imkoniyatlar</a><a href="#how">Qanday ishlaydi?</a></div>
        <div className="nav-actions"><Link href="/login" className="login-link">Kirish</Link><Link href="/register" className="nav-cta">Boshlash <span>→</span></Link></div>
      </nav>

      <section className="hero">
        <div className="hero-bg"/><div className="hero-grid"/>
        <div className="eyebrow"><i className="dot"/> MILLIY SERTIFIKAT UCHUN TAYYORGARLIK</div>
        <h1>Imtihonga tayyorlanishning <em>yaxshiroq yo‘li.</em></h1>
        <p className="hero-sub">Faningizni tanlang, savollarni ishlang, natijangizni kuzating va imtihon kunigacha tayyorgarligingizni tartibli olib boring.</p>
        <div className="actions"><Link href="/register" className="button button-main">Bepul boshlash <span>→</span></Link><a href="#subjects" className="button button-ghost">Fanlarni ko‘rish</a></div>
        <div className="proof"><span>✓ Practice</span><span>✓ Question Bank</span><span>✓ Oson / O‘rta / Qiyin</span><span>✓ Shaxsiy reja</span></div>
        <div className="scrollhint">PASTGA O‘TING <b>↓</b></div>
      </section>

      <section id="subjects" className="section">
        <div className="section-head"><div><div className="eyebrow-small">FANLAR</div><h2>Kerakli faningizdan boshlang.</h2></div><p>Har bir fan uchun mashq qilish, savollarni topish va natijani kuzatish imkoniyati bir joyda.</p></div>
        <div className="subjects">{subjects.map(([name,icon,group,href])=><Link className="subject" href={href} key={name}><div className="subject-icon">{icon}</div><small>{group}</small><h3>{name}</h3><span className="subject-arrow">→</span></Link>)}</div>
      </section>

      <section id="features" className="showcase"><div className="section"><div className="section-head"><div><div className="eyebrow-small">ASOSIY IMKONIYATLAR</div><h2>Tayyorgarlikning hammasi bir joyda.</h2></div><p>Ortiqcha murakkabliksiz: ishlang, tekshiring, xatolaringizni ko‘ring va keyingi qadamni belgilang.</p></div><div className="feature-grid">{features.map(([n,t,d])=><article className="feature" key={n}><div className="feature-number">{n}</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

      <section id="how" className="section"><div className="workflow"><div className="workflow-copy"><div className="eyebrow-small">QANDAY ISHLAYDI?</div><h2>Bugun boshlang. Har kuni yaxshilaning.</h2><p>MilliyTest tayyorgarlikni oddiy ketma-ketlikka aylantiradi: maqsad → fan → mashq → natija.</p><div className="mini-dashboard"><div className="dash-window"><div className="dash-head"><b>Bugungi tayyorgarlik</b><span className="dash-dots"><i/><i/><i/></span></div><div className="dash-body"><div className="dash-card"><small>Progress</small><strong>72%</strong><div className="dash-line"><span/></div></div><div className="dash-card"><small>Target</small><strong>A+</strong><div className="dash-line"><span/></div></div></div></div></div></div><div className="steps">{steps.map(([n,t,d])=><div className="step" key={n}><span className="step-number">{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>

      <section className="cta"><div><div className="eyebrow-small">TAYYORMISIZ?</div><h2>Imtihonga tayyorgarlikni bugun boshlang.</h2></div><Link href="/register" className="button button-main">Bepul hisob yaratish →</Link></section>

      <footer><strong>MilliyTest</strong><span>Milliy sertifikat imtihonlariga tayyorgarlik platformasi.</span><div className="footer-links"><Link href="/login">Kirish</Link><Link href="/register">Ro‘yxatdan o‘tish</Link></div></footer>
    </main>
  );
}
