'use client';
import {FormEvent,Suspense,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {createClient} from '@/lib/supabase';

type Option={key:'A'|'B'|'C'|'D';text:string};

function EditQuestionForm(){
 const supabase=createClient();const router=useRouter();const params=useSearchParams();const id=params.get('id')||'';
 const [subjects,setSubjects]=useState<any[]>([]),[topics,setTopics]=useState<any[]>([]),[subjectId,setSubjectId]=useState(''),[topicId,setTopicId]=useState(''),[text,setText]=useState(''),[explanation,setExplanation]=useState(''),[difficulty,setDifficulty]=useState('medium'),[status,setStatus]=useState('draft'),[sourceType,setSourceType]=useState('sample'),[source,setSource]=useState(''),[correct,setCorrect]=useState<'A'|'B'|'C'|'D'>('A'),[opts,setOpts]=useState<Option[]>([{key:'A',text:''},{key:'B',text:''},{key:'C',text:''},{key:'D',text:''}]),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{if(!id){setLoading(false);return}const [{data:s},{data:q}]=await Promise.all([supabase.from('subjects').select('*').order('sort_order'),supabase.from('questions').select('*').eq('id',id).maybeSingle()]);setSubjects(s??[]);if(q){setSubjectId(q.subject_id);setTopicId(q.topic_id||'');setText(q.text);setExplanation(q.explanation||'');setDifficulty(q.difficulty);setStatus(q.status);setSourceType(q.source_type);setSource(q.source||'');const {data:o}=await supabase.from('question_options').select('option_key,option_text').eq('question_id',id).order('sort_order');if(o?.length)setOpts(o.map((x:any)=>({key:x.option_key,text:x.option_text})));const {data:t}=await supabase.from('topics').select('*').eq('subject_id',q.subject_id).order('sort_order');setTopics(t??[]);const {data:c}=await supabase.from('question_options').select('option_key').eq('question_id',id).eq('is_correct',true).maybeSingle();if(c?.option_key)setCorrect(c.option_key)}setLoading(false)})()},[id]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');const r=await fetch(`/api/admin/questions/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({subjectId,topicId:topicId||null,text,explanation:explanation||null,difficulty,status,sourceType,source:source||null,options:opts,correctAnswer:correct})});const j=await r.json();if(!r.ok)setMessage(j.error||'Saqlashda xato');else{setMessage('Savol yangilandi.');router.push('/admin/questions')}setSaving(false)}
 async function archive(){if(!window.confirm('Savolni archive qilishni xohlaysizmi?'))return;const r=await fetch(`/api/admin/questions/${id}`,{method:'DELETE'});if(r.ok)router.push('/admin/questions');else{const j=await r.json();setMessage(j.error||'Archive xatosi')}}
 if(loading)return <main className="dash-shell"><section className="dash-wrap">Yuklanmoqda…</section></main>;
 return <main className="dash-shell"><header className="dash-nav"><Link href="/admin/questions">← Savollar</Link><button className="secondary" onClick={archive}>Archive</button></header><section className="dash-wrap"><div className="kicker">EDIT QUESTION</div><h1>Savolni tahrirlash.</h1><form className="form-card" onSubmit={save}><label>Fan<select value={subjectId} required onChange={e=>{setSubjectId(e.target.value);setTopicId('');supabase.from('topics').select('*').eq('subject_id',e.target.value).order('sort_order').then(({data})=>setTopics(data??[]))}}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Mavzu<select value={topicId} onChange={e=>setTopicId(e.target.value)}><option value="">Tanlang</option>{topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Savol<textarea value={text} onChange={e=>setText(e.target.value)} required rows={5}/></label>{opts.map((o)=><label key={o.key}>{o.key} variant<input required value={o.text} onChange={e=>setOpts(a=>a.map(x=>x.key===o.key?{...x,text:e.target.value}:x))}/></label>)}<label>To‘g‘ri javob<select value={correct} onChange={e=>setCorrect(e.target.value as 'A'|'B'|'C'|'D')}>{opts.map(o=><option key={o.key}>{o.key}</option>)}</select></label><label>Explanation<textarea value={explanation} onChange={e=>setExplanation(e.target.value)} rows={4}/></label><label>Manba<input value={source} onChange={e=>setSource(e.target.value)}/></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>easy</option><option>medium</option><option>hard</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option>draft</option><option>published</option><option>archived</option></select></label><label>Source type<select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option>sample</option><option>practice</option><option>verified</option><option>ai_generated</option></select></label>{message&&<div className="success-box">{message}</div>}<button className="primary" disabled={saving}>{saving?'Saqlanmoqda…':'Saqlash'}</button></form></section></main>
}

export default function EditQuestion(){return <Suspense fallback={<main className="dash-shell"><section className="dash-wrap">Yuklanmoqda…</section></main>}><EditQuestionForm/></Suspense>}
