'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Subject={id:string;name:string}; type Topic={id:string;name:string;subject_id:string};
export default function NewQuestion(){
 const [subjects,setSubjects]=useState<Subject[]>([]),[topics,setTopics]=useState<Topic[]>([]),[subjectId,setSubjectId]=useState(''),[topicId,setTopicId]=useState(''),[text,setText]=useState(''),[opts,setOpts]=useState(['','','','']),[correct,setCorrect]=useState('A'),[difficulty,setDifficulty]=useState('medium'),[explanation,setExplanation]=useState(''),[published,setPublished]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/admin/catalog').then(r=>r.ok?r.json():null).then(j=>setSubjects(j?.subjects??[])).catch(()=>setError('Fanlarni yuklashda xatolik.'))},[]);
 useEffect(()=>{if(!subjectId)return;fetch(`/api/admin/catalog?subjectId=${subjectId}`).then(r=>r.ok?r.json():null).then(j=>setTopics(j?.topics??[])).catch(()=>setError('Mavzularni yuklashda xatolik.'))},[subjectId]);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage('');setError('');setBusy(true);try{const r=await fetch('/api/admin/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjectId,topicId,text,options:opts.map((x,i)=>({key:String.fromCharCode(65+i),text:x})),correctAnswer:correct,difficulty,explanation,published})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Question could not be created');setMessage('Question created successfully');setText('');setOpts(['','','','']);setExplanation('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <main className="dash-shell"><header className="dash-nav"><Link href="/admin/questions">← Savollar</Link></header><section className="dash-wrap"><div className="kicker">NEW QUESTION</div><h1>Yangi savol.</h1><form className="form-card" onSubmit={submit}><label>Fan<select value={subjectId} required onChange={e=>{setSubjectId(e.target.value);setTopicId('')}}><option value="">Tanlang</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Mavzu<select value={topicId} required onChange={e=>setTopicId(e.target.value)}><option value="">Tanlang</option>{topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Savol<textarea value={text} onChange={e=>setText(e.target.value)} required rows={4}/></label>{opts.map((o,i)=><label key={i}>{String.fromCharCode(65+i)} variant<input value={o} onChange={e=>setOpts(a=>a.map((x,j)=>j===i?e.target.value:x))} required /></label>)}<label>To‘g‘ri javob<select value={correct} onChange={e=>setCorrect(e.target.value)}>{['A','B','C','D'].map(x=><option key={x}>{x}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>easy</option><option>medium</option><option>hard</option></select></label><label>Explanation<textarea value={explanation} onChange={e=>setExplanation(e.target.value)} rows={3}/></label><label><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> Published</label>{message&&<div className="success-box">{message}</div>}{error&&<div className="error-box">{error}</div>}<button className="primary" disabled={busy}>{busy?'Saqlanmoqda...':'Saqlash'}</button></form></section></main>;
}
