'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase';

type Row={subjectId:string;topicId:string|null;text:string;explanation:string|null;difficulty:'easy'|'medium'|'hard';status:'draft'|'published'|'archived';sourceType:'sample'|'practice'|'verified';source:string|null;options:{key:'A'|'B'|'C'|'D';text:string}[];correctAnswer:'A'|'B'|'C'|'D'};
const keys=['A','B','C','D'] as const;
function parseCsv(input:string){const lines=input.split(/\r?\n/).filter(Boolean);if(!lines.length)return [];const split=(s:string)=>{const out:string[]=[];let cur='',quote=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'&&s[i+1]==='"'){cur+='"';i++;continue}if(c==='"'){quote=!quote;continue}if(c===','&&!quote){out.push(cur.trim());cur='';continue}cur+=c}out.push(cur.trim());return out};const headers=split(lines[0]).map(x=>x.toLowerCase());return lines.slice(1).map(line=>{const vals=split(line);return Object.fromEntries(headers.map((h,i)=>[h,vals[i]??'']));});}
export default function ImportQuestions(){
 const supabase=createClient();const [subjects,setSubjects]=useState<any[]>([]),[topics,setTopics]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[fileName,setFileName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{supabase.from('subjects').select('id,name').order('sort_order').then(({data})=>setSubjects(data??[]))},[supabase]);
 const makeRows=(raw:any[])=>{const result=raw.map((r:any)=>{const subject=subjects.find(s=>s.id===r.subjectId||s.name.trim().toLowerCase()===String(r.subject||'').trim().toLowerCase());return {subjectId:subject?.id||r.subjectId||'',topicId:r.topicId||null,text:r.text||r.question||'',explanation:r.explanation||null,difficulty:(r.difficulty||'medium').toLowerCase(),status:(r.status||'draft').toLowerCase(),sourceType:r.sourceType||r.source_type||'sample',source:r.source||null,options:keys.map(k=>({key:k,text:r[`option${k}`]||r[k]||''})),correctAnswer:(r.correctAnswer||r.correct_answer||'A').toUpperCase()}});setRows(result)};
 const load=async(file:File)=>{setFileName(file.name);setMessage('');const text=await file.text();try{const raw=file.name.toLowerCase().endsWith('.json')?JSON.parse(text):parseCsv(text);if(!Array.isArray(raw))throw new Error('JSON array bo‘lishi kerak.');makeRows(raw)}catch(e:any){setRows([]);setMessage(e.message||'Faylni o‘qib bo‘lmadi.')}};
 const submit=async()=>{setMessage('');if(!rows.length)return;setBusy(true);try{const res=await fetch('/api/admin/questions/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Import xatosi');setMessage(`${data.inserted} ta savol qo‘shildi, ${data.skipped} ta duplicate/skipped.`);setRows([])}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 return <main className="dash-shell"><header className="dash-nav"><Link href="/admin/questions" className="brand">← Savollar</Link><span>Bulk Import</span></header><section className="dash-wrap"><div className="kicker">QUESTION BANK · IMPORT</div><h1>CSV / JSON import.</h1><p className="lead">Bir martada 500 tagacha admin savolini yuklang. Duplicate savollar avtomatik o‘tkazib yuboriladi.</p><div className="panel"><h2>1. Fayl tanlang</h2><p>CSV ustunlari: subjectId yoki subject, topicId, text, optionA, optionB, optionC, optionD, correctAnswer, explanation, difficulty, status, sourceType, source.</p><input type="file" accept=".csv,.json,application/json,text/csv" onChange={e=>e.target.files?.[0]&&load(e.target.files[0])}/>{fileName&&<p><b>{fileName}</b></p>}</div>{rows.length>0&&<div className="panel"><div className="panel-title"><h2>2. Preview</h2><span>{rows.length} ta</span></div><div className="admin-list">{rows.slice(0,20).map((r,i)=><article className="panel" key={i}><b>{i+1}. {r.text||'Savol matni yo‘q'}</b><p>{r.options.filter((o:any)=>o.text).map((o:any)=>`${o.key}: ${o.text}`).join(' · ')}</p><small>{r.difficulty} · {r.status} · correct: {r.correctAnswer}</small></article>)}</div>{rows.length>20&&<p>Faqat dastlabki 20 tasi previewda ko‘rsatilmoqda.</p>}<button className="primary" disabled={busy} onClick={submit}>{busy?'Import qilinmoqda…':`${rows.length} ta savolni import qilish →`}</button></div>}{message&&<div className="result-card"><p>{message}</p></div>}<div className="panel"><h2>Namuna format</h2><p>CSV: <code>subject,topic,text,optionA,optionB,optionC,optionD,correctAnswer,difficulty</code></p><p>JSON: har bir obyekt shu maydonlardan foydalanadi.</p></div></section></main>;
}
