-- National Certificate AI MVP schema.
-- This migration mirrors the production Supabase schema applied on 2026-08-28.
create extension if not exists pgcrypto;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text,username text unique,avatar_url text,preferred_language text not null default 'uz' check(preferred_language in('uz','ru','en')),target_score integer,exam_date date,current_level text,daily_study_minutes integer not null default 60,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.user_roles(user_id uuid primary key references auth.users(id) on delete cascade,role text not null default 'student' check(role in('student','admin')),created_at timestamptz not null default now());
create table if not exists public.subjects(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text,icon text,sort_order integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.topics(id uuid primary key default gen_random_uuid(),subject_id uuid not null references public.subjects(id) on delete cascade,name text not null,slug text not null,description text,sort_order integer not null default 0,unique(subject_id,slug));
create table if not exists public.subtopics(id uuid primary key default gen_random_uuid(),topic_id uuid not null references public.topics(id) on delete cascade,name text not null,slug text not null,sort_order integer not null default 0,unique(topic_id,slug));
create table if not exists public.questions(id uuid primary key default gen_random_uuid(),subject_id uuid not null references public.subjects(id) on delete cascade,topic_id uuid references public.topics(id) on delete set null,subtopic_id uuid references public.subtopics(id) on delete set null,text text not null,question_type text not null default 'multiple_choice',difficulty text not null default 'medium',explanation text,source text,source_type text not null default 'sample',image_url text,tags text[] not null default '{}',status text not null default 'draft',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.question_options(id uuid primary key default gen_random_uuid(),question_id uuid not null references public.questions(id) on delete cascade,option_text text not null,option_key text not null,sort_order integer not null default 0,is_correct boolean not null default false,unique(question_id,option_key));
create table if not exists public.tests(id uuid primary key default gen_random_uuid(),subject_id uuid references public.subjects(id) on delete set null,title text not null,mode text not null default 'mock',duration_minutes integer,question_count integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.test_questions(test_id uuid not null references public.tests(id) on delete cascade,question_id uuid not null references public.questions(id) on delete cascade,position integer not null,primary key(test_id,question_id),unique(test_id,position));
create table if not exists public.test_attempts(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,test_id uuid references public.tests(id) on delete set null,subject_id uuid references public.subjects(id) on delete set null,started_at timestamptz not null default now(),completed_at timestamptz,score numeric(6,2),correct_count integer not null default 0,total_count integer not null default 0,time_spent_seconds integer not null default 0,mode text not null default 'practice');
create table if not exists public.answers(id uuid primary key default gen_random_uuid(),attempt_id uuid not null references public.test_attempts(id) on delete cascade,question_id uuid not null references public.questions(id) on delete cascade,selected_answer text,is_correct boolean not null default false,time_spent_seconds integer not null default 0,answered_at timestamptz not null default now(),unique(attempt_id,question_id));
create table if not exists public.topic_progress(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,topic_id uuid not null references public.topics(id) on delete cascade,attempted integer not null default 0,correct integer not null default 0,accuracy numeric(6,2) not null default 0,updated_at timestamptz not null default now(),unique(user_id,topic_id));
create table if not exists public.study_sessions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,subject_id uuid references public.subjects(id) on delete set null,topic_id uuid references public.topics(id) on delete set null,started_at timestamptz not null default now(),duration_seconds integer not null default 0,completed boolean not null default false);
create table if not exists public.recommendations(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,subject_id uuid references public.subjects(id) on delete set null,topic_id uuid references public.topics(id) on delete set null,kind text not null,title text not null,reason text,priority integer not null default 0,completed boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.ai_conversations(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,subject_id uuid references public.subjects(id) on delete set null,title text,created_at timestamptz not null default now());
create table if not exists public.ai_messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references public.ai_conversations(id) on delete cascade,role text not null check(role in('user','assistant','system')),content text not null,created_at timestamptz not null default now());
create table if not exists public.user_subjects(user_id uuid not null references auth.users(id) on delete cascade,subject_id uuid not null references public.subjects(id) on delete cascade,primary key(user_id,subject_id));
create table if not exists public.study_plans(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,exam_date date not null,target_score integer,daily_minutes integer not null,generated_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.study_plan_items(id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.study_plans(id) on delete cascade,subject_id uuid references public.subjects(id) on delete set null,topic_id uuid references public.topics(id) on delete set null,plan_date date not null,minutes integer not null,activity_type text not null,title text not null,completed boolean not null default false);

create index if not exists questions_subject_topic_idx on public.questions(subject_id,topic_id,status);
create index if not exists attempts_user_idx on public.test_attempts(user_id,started_at desc);
create index if not exists answers_attempt_idx on public.answers(attempt_id);
create index if not exists progress_user_idx on public.topic_progress(user_id,accuracy);

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.subjects enable row level security; alter table public.topics enable row level security; alter table public.subtopics enable row level security; alter table public.questions enable row level security; alter table public.question_options enable row level security; alter table public.tests enable row level security; alter table public.test_questions enable row level security; alter table public.test_attempts enable row level security; alter table public.answers enable row level security; alter table public.topic_progress enable row level security; alter table public.study_sessions enable row level security; alter table public.recommendations enable row level security; alter table public.ai_conversations enable row level security; alter table public.ai_messages enable row level security; alter table public.user_subjects enable row level security; alter table public.study_plans enable row level security; alter table public.study_plan_items enable row level security;

-- Authorization helper uses database role, never user-editable metadata.
create schema if not exists private;
create or replace function private.is_admin() returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from public.user_roles where user_id=auth.uid() and role='admin')$$;
revoke all on function private.is_admin() from public; grant execute on function private.is_admin() to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin insert into public.profiles(id,name) values(new.id,coalesce(new.raw_user_meta_data->>'name','')) on conflict(id) do nothing; insert into public.user_roles(user_id,role) values(new.id,'student') on conflict(user_id) do nothing; return new; end$$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create policy profiles_owner_select on public.profiles for select to authenticated using(id=auth.uid());
create policy profiles_owner_insert on public.profiles for insert to authenticated with check(id=auth.uid());
create policy profiles_owner_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy roles_owner_select on public.user_roles for select to authenticated using(user_id=auth.uid() or private.is_admin());
create policy subjects_public_select on public.subjects for select using(true); create policy topics_public_select on public.topics for select using(true); create policy subtopics_public_select on public.subtopics for select using(true);
create policy questions_published_select on public.questions for select to authenticated using(status='published'); create policy questions_admin_all on public.questions for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy options_published_select on public.question_options for select to authenticated using(exists(select 1 from public.questions q where q.id=question_id and q.status='published')); create policy options_admin_all on public.question_options for all to authenticated using(private.is_admin()) with check(private.is_admin());
create policy tests_public_select on public.tests for select using(true); create policy test_questions_public_select on public.test_questions for select using(true);
create policy attempts_owner_all on public.test_attempts for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy answers_owner_all on public.answers for all to authenticated using(exists(select 1 from public.test_attempts a where a.id=attempt_id and a.user_id=auth.uid())) with check(exists(select 1 from public.test_attempts a where a.id=attempt_id and a.user_id=auth.uid()));
create policy progress_owner_all on public.topic_progress for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy sessions_owner_all on public.study_sessions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy recommendations_owner_all on public.recommendations for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy conversations_owner_all on public.ai_conversations for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy messages_owner_all on public.ai_messages for all to authenticated using(exists(select 1 from public.ai_conversations c where c.id=conversation_id and c.user_id=auth.uid())) with check(exists(select 1 from public.ai_conversations c where c.id=conversation_id and c.user_id=auth.uid()));
create policy user_subjects_owner_all on public.user_subjects for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy plans_owner_all on public.study_plans for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy plan_items_owner_all on public.study_plan_items for all to authenticated using(exists(select 1 from public.study_plans p where p.id=plan_id and p.user_id=auth.uid())) with check(exists(select 1 from public.study_plans p where p.id=plan_id and p.user_id=auth.uid()));

create or replace function public.submit_answer(p_attempt_id uuid,p_question_id uuid,p_selected_answer text,p_time_spent_seconds integer default 0) returns table(is_correct boolean,correct_answer text) language plpgsql security definer set search_path=public,pg_temp as $$declare v_user uuid;v_correct text;v_ok boolean;begin select user_id into v_user from public.test_attempts where id=p_attempt_id;if v_user is null or v_user<>auth.uid() then raise exception 'Not authorized';end if;select option_key into v_correct from public.question_options where question_id=p_question_id and is_correct=true limit 1;v_ok:=coalesce(p_selected_answer,'')=coalesce(v_correct,'');insert into public.answers(attempt_id,question_id,selected_answer,is_correct,time_spent_seconds) values(p_attempt_id,p_question_id,p_selected_answer,v_ok,greatest(0,p_time_spent_seconds)) on conflict(attempt_id,question_id) do update set selected_answer=excluded.selected_answer,is_correct=excluded.is_correct,time_spent_seconds=excluded.time_spent_seconds,answered_at=now();return query select v_ok,v_correct;end$$;
revoke all on function public.submit_answer(uuid,uuid,text,integer) from public; grant execute on function public.submit_answer(uuid,uuid,text,integer) to authenticated;

create view public.practice_questions with(security_invoker=true) as select q.id,q.subject_id,q.topic_id,q.subtopic_id,q.text,q.question_type,q.difficulty,q.explanation,q.source,q.source_type,q.image_url,q.tags,coalesce(jsonb_agg(jsonb_build_object('id',o.id,'text',o.option_text,'key',o.option_key,'order',o.sort_order) order by o.sort_order) filter(where o.id is not null),'[]'::jsonb) options from public.questions q left join public.question_options o on o.question_id=q.id where q.status='published' group by q.id;
grant select on public.practice_questions to authenticated;
