'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';

type Subject={id:string;name:string};
type Topic={id:string;name:string;subject_id:string};
type Option={option_key:string;option_text:string;is_correct:boolean;sort_order:number};
type Question={id:string;text:string;status:string;difficulty:string;explanation:string|null;created_at:string;subject_id:string;topic_id:string;subjects?:{name:string}|null;topics?:{name:string}|null;question_options?:Option[]};

export default function QuestionsManager({initialQuestions,subjects,topics,total}:{initialQuestions:Question[];subjects:Subject[];topics:Topic[];total:number}){
 const [questions,setQuestions]=useState(initialQuestions),[search,setSearch]=useState(''),[subject,setSubject]=useState(''),[topic,setTopic]=useState(''),[difficulty,setDifficulty]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[count,setCount]=useState(total),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Question|null>(null),[importOpen,setImportOpen]=useState(false);
 const filteredTopics=useMemo(()=>topics.filter(t=>!subject||t.subject_id===subject),[topics,subject]);
 async function load(p=page){setBusy('load');setError('');try{const q=new URLSearchParams({page:String(p),limit:'25'});if(search)q.set('search',search);if(subject)q.set('subjectId',subject);if(topic)q.set('topicId',topic);if(difficulty)q.set('difficulty',difficulty);if(status)q.set('status',status);const r=await fetch(`/api/admin/questions?${q}`);const j=await r.json();if(!r.ok)throw new Error(j.error);setQuestions(j.data);setCount(j.count);setPage(p);}catch(e:any){setError(e.message||'Savollarni yuklashda xatolik.');}finally{setBusy('');}}
 useEffect(()=>{const t=setTimeout(()=>load(1),250);return()=>clearTimeout(t)},[search,subject,topic,difficulty,status]);
 async function action(id:string,method:'PATCH'|'DELETE',body?:unknown){setBusy(id);setError('');setMessage('');try{let payload=body;if(method==='PATCH'&&!body)payload={};const r=await fetch(`/api/admin/questions/${id}`,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error);setMessage(method==='DELETE'?'Savol o‘chirildi.':'Holat yangilandi.');await load(page);}catch(e:any){setError(e.message||'Amal bajarilmadi.');}finally{setBusy('');}}
 async function toggle(q:Question){const published=q.status!=='published';const opts=(q.question_options??[]).sort((a,b)=>a.sort_order-b.sort_order);await action(q.id,'PATCH',{subjectId:q.subject_id,topicId:q.topic_id,text:q.text,options:opts.map(o=>({key:o.option_key as 'A'|'B'|'C'|'D',text:o.option_text})),correctAnswer:(opts.find(o=>o.is_correct)?.option_key||'A') as 'A'|'B'|'C'|'D',difficulty:q.difficulty,explanation:q.explanation||'',published});}
 return <>
  <div className="admin-toolbar"><input aria-label="Savol qidirish" placeholder="Savol matnidan qidiring..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={subject} onChange={e=>{setSubject(e.target.value);setTopic('')}}><option value="">Barcha fanlar</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">Barcha mavzular</option>{filteredTopics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="">Qiyinchilik</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Barcha holatlar</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></div>
  <div className="admin-actions"><Link className="primary" href="/admin/questions/new">+ Yangi savol</Link><button className="secondary" onClick={()=>setImportOpen(true)}>Import Questions</button></div>
  {busy==='load'&&<div className="panel">Yuklanmoqda...</div>}{error&&<div className="error-box">{error} <button onClick={()=>load(page)}>Qayta urinish</button></div>}{message&&<div className="success-box">{message}</div>}
  {!busy&&questions.length===0?<div className="panel"><h2>Savollar topilmadi.</h2><p>Filterlarni o‘zgartirib ko‘ring yoki yangi savol qo‘shing.</p></div>:<div className="admin-list">{questions.map(q=><article className="panel admin-question" key={q.id}><div><span className="status">{q.status}</span><h2>{q.text}</h2><p>{q.subjects?.name} · {q.topics?.name} · {q.difficulty} · {new Date(q.created_at).toLocaleDateString('uz-UZ')}</p></div><div className="row-actions"><button disabled={!!busy} onClick={()=>setEditing(q)}>Edit</button><button disabled={!!busy} onClick={()=>toggle(q)}>{q.status==='published'?'Unpublish':'Publish'}</button><button disabled={!!busy} onClick={()=>{if(confirm('Bu savolni o‘chirishni xohlaysizmi?'))action(q.id,'DELETE')}}>Delete</button></div></article>)}</div>}
  {count>25&&<div className="pagination"><button disabled={page<=1||!!busy} onClick={()=>load(page-1)}>← Oldingi</button><span>{page} / {Math.ceil(count/25)}</span><button disabled={page>=Math.ceil(count/25)||!!busy} onClick={()=>load(page+1)}>Keyingi →</button></div>}
  {editing&&<QuestionEditor question={editing} subjects={subjects} topics={topics} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);setMessage('Question updated successfully');await load(page)}}/>}
  {importOpen&&<ImportModal onClose={()=>setImportOpen(false)} onDone={async(msg)=>{setImportOpen(false);setMessage(msg);await load(1)}}/>}
 </>;
}

function QuestionEditor({question,subjects,topics,onClose,onSaved}:{question:Question;subjects:Subject[];topics:Topic[];onClose:()=>void;onSaved:()=>Promise<void>}){const opts=(question.question_options??[]).sort((a,b)=>a.sort_order-b.sort_order);const [subjectId,setSubjectId]=useState(question.subject_id),[topicId,setTopicId]=useState(question.topic_id),[text,setText]=useState(question.text),[options,setOptions]=useState(opts.map(o=>o.option_text)),[correct,setCorrect]=useState(opts.find(o=>o.is_correct)?.option_key||'A'),[difficulty,setDifficulty]=useState(question.difficulty),[explanation,setExplanation]=useState(question.explanation||''),[published,setPublished]=useState(question.status==='published'),[busy,setBusy]=useState(false),[error,setError]=useState('');const ts=topics.filter(t=>t.subject_id===subjectId);async function save(){setBusy(true);setError('');try{const r=await fetch(`/api/admin/questions/${question.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({subjectId,topicId,text,options:options.map((x,i)=>({key:String.fromCharCode(65+i),text:x})),correctAnswer:correct,difficulty,explanation,published})});const j=await r.json();if(!r.ok)throw new Error(j.error);await onSaved()}catch(e:any){setError(e.message||'Question could not be updated')}finally{setBusy(false)}}return <div className="modal-backdrop"><div className="modal"><h2>Edit question</h2><label>Fan<select value={subjectId} onChange={e=>{setSubjectId(e.target.value);setTopicId('')}}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Mavzu<select value={topicId} onChange={e=>setTopicId(e.target.value)}>{ts.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Savol<textarea value={text} onChange={e=>setText(e.target.value)}/></label>{options.map((x,i)=><label key={i}>{String.fromCharCode(65+i)} variant<input value={x} onChange={e=>setOptions(a=>a.map((v,j)=>j===i?e.target.value:v))}/></label>)}<label>To‘g‘ri javob<select value={correct} onChange={e=>setCorrect(e.target.value)}>{['A','B','C','D'].map(x=><option key={x}>{x}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>easy</option><option>medium</option><option>hard</option></select></label><label>Explanation<textarea value={explanation} onChange={e=>setExplanation(e.target.value)}/></label><label><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> Published</label>{error&&<div className="error-box">{error}</div>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={save}>{busy?'Saqlanmoqda...':'Save'}</button></div></div></div>}

function ImportModal({onClose,onDone}:{onClose:()=>void;onDone:(message:string)=>Promise<void>}){const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');async function importFile(){if(!file)return;setBusy(true);setError('');try{const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('CSV bo‘sh.');const headers=lines[0].split(',').map(x=>x.trim());const required=['subject','topic','question','option_a','option_b','option_c','option_d','correct_answer','difficulty','explanation','published'];if(required.some(x=>!headers.includes(x)))throw new Error('CSV columns noto‘g‘ri.');const rows=lines.slice(1).map(line=>{const vals=parseCsvLine(line);const r=Object.fromEntries(headers.map((h,i)=>[h,vals[i]??'']));return {subject:r.subject,topic:r.topic,question:r.question,options:[r.option_a,r.option_b,r.option_c,r.option_d],correctAnswer:r.correct_answer,difficulty:r.difficulty,status:String(r.published).toLowerCase()==='true'?'published':'draft',sourceType:'sample'};});const res=await fetch('/api/admin/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows})});const j=await res.json();if(!res.ok)throw new Error(j.errors?.map((e:any)=>`Row ${e.row}: ${e.error}`).join('\n')||j.error);await onDone(`Import tugadi: ${j.inserted} qo‘shildi, ${j.skipped||0} duplicate skip qilindi.`)}catch(e:any){setError(e.message||'Import failed')}finally{setBusy(false)}}return <div className="modal-backdrop"><div className="modal"><h2>Import Questions</h2><p>CSV: subject, topic, question, option_a, option_b, option_c, option_d, correct_answer, difficulty, explanation, published</p><input type="file" accept=".csv,text/csv" onChange={e=>setFile(e.target.files?.[0]||null)}/>{error&&<pre className="error-box">{error}</pre>}<div className="modal-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!file||busy} onClick={importFile}>{busy?'Import qilinmoqda...':'Import'}</button></div></div></div>}
function parseCsvLine(line:string){const out:string[]=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(cur.trim());cur='';}else cur+=c;}out.push(cur.trim());return out;}
